[package]
name = "runn-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.139"
serde_yaml = "0.9.34"
schemars = "0.8.21"
glob = "0.3.2"
tower-lsp = "0.20.0"
tokio = { version = "1.43.0", features = ["macros"] }
